name: Kubernetes

on:
  workflow_call:

jobs:

  EKS:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configurando Credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ID_CHAVE_ACESSO }}
        aws-secret-access-key: ${{ secrets.CHAVE_SECRETA }}
        aws-region: us-east-2

    - run: git clone https://github.com/hugorebonato/Infra_CI_Kubernetes.git

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      
    - run: terraform -chdir=Infra_CI_Kubernetes/env/Homolog init

    - run: terraform -chdir=Infra_CI_Kubernetes/env/Homolog apply -auto-approve

    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v4.0.0
       
    - run: aws sts get-caller-identity

    - run: aws eks update-kubeconfig --region us-east-1 --name homolog2

    - run: kubectl get svc
    
    - run: kubectl create secret generic dbhost --from-literal=HOST= 
    - run: kubectl create secret generic dbport --from-literal=DBPORT=
    - run: kubectl create secret generic dbuser --from-literal=USER= 
    - run: kubectl create secret generic dbpassword --from-literal=PASSWORD= 
    - run: kubectl create secret generic dbname --from-literal=DBNAME= 
    - run: kubectl create secret generic port --from-literal=PORT= 
    
